# Micronaut configuration
micronaut:

# Security settings
  security:
    enabled: true
    basic-auth:
      enabled: true
    authentication: session
    session:
      enabled: true
    redirect:
      logout: /status/info
      login-success: /login/authSuccess
      login-failure: /login/authFailed

# Enable /login and /logout default endpoints
    endpoints:
      login:
        enabled: true
        path: /login
      logout:
        enabled: true
        path: /logout

# Enable endpoints for unauthenticated user with GET
    intercept-url-map:
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()

# Path /v1/** only for authenticated users
      - pattern: /v1/**
        access:
          - isAuthenticated()

# Make rules for cors
  server:
    cors:
      enabled: true
      configurations:
#        all:
#          allowed-origins:
#            - http://127.0.0.1:4200

# Allow cors for front-end app
        web:
          allowed-origins:
            - http://127.0.0.1:4200
